
services:
  ace:
    build:
      context: .
      dockerfile: Dockerfile.ace
    container_name: ace-container
    image: ibmcom/ace:latest
    ports:
      - "7600:7600"
      - "7800:7800"
    volumes:
      - /Users/jcarlo/IBM/ACET12/workspace/GeneratedBarFiles:/home/aceuser/ace-server-data/bars
      - ./config/server.conf.yaml:/home/aceuser/ace-server-data/configuration/server.conf.yaml
      - ./drivers/mysql-connector-j-9.4.0/mysql-connector-j-9.4.0.jar:/home/aceuser/ace-server-data/shared-classes/mysql-connector-j-9.4.0.jar
    environment:
      ACE_SERVER_NAME: default
      LICENSE: accept
      ACE_DEBUG: "true"
    depends_on:
      mq:
        condition: service_started
      kafka:
        condition: service_started
      mysql:
        condition: service_healthy
    networks:
      - ace-mq-network

  mq:
    build:
      context: .
      dockerfile: Dockerfile.mq
    container_name: mq-container
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
    networks:
      - ace-mq-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - ace-mq-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_PROCESS_ROLES: broker
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: MkafkaCluster1234567890
    ports:
      - "9092:9092"
    networks:
      - ace-mq-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: localhost:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: localhost:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      - ace-mq-network

  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: aceuser
      MYSQL_PASSWORD: acepass
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ace-mq-network

volumes:
  mysql-data:

networks:
  ace-mq-network:
    driver: bridge
