name: default

connectors:
  mq:
    queueManager: QM1
    connection:
      host: mq-container
      port: 1414
      channel: DEV.ADMIN.SVRCONN
    security:
      username: mqadmin
      password: mqpassword

RestApi:
  port: 7800

logging:
  console:
    logLevel: info
  file:
    enabled: true
    directory: '/home/aceuser/ace-server/log'
    logLevel: info

resources:
  JDBCProviders:
    MySQLJDBC:
      connectionUrlFormat: 'jdbc:mysql://{serverName}:{port}/{databaseName}'
      connectionUrlFormatAttr:
        serverName: mysql-db
        port: 3306
        databaseName: test
      databaseName: test
      jarsURL: '/home/aceuser/ace-server/shared-classes/mysql-connector-j-9.4.0.jar'
      type4DriverClassName: 'com.mysql.cj.jdbc.Driver'
