server:
  name: default
  connectors:
    mq:
      queueManager: QM1
      connection:
        host: mq-container
        port: 1414
        channel: DEV.ADMIN.SVRCONN
      security:
        username: mqadmin
        password: mqpassword  
  RestApi:
    port: 7800
  Logging:
    console:
      logLevel: info
    file:
      enabled: true
      directory: /home/aceuser/ace-server/log
      logLevel: info  
  JDBCProviders:
  MySQLProvider:
    databaseName: mydb
    type4DriverClassName: com.mysql.cj.jdbc.Driver
    connectionUrlFormat: jdbc:mysql://mysql-db:3306/mydb
    jarsURL: /home/aceuser/ace-server-data/shared-classes/mysql-connector-j-9.4.0.jar
    
